### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by deiteris** [api-components/amf-components#2]
Hello @jarrodek,

If I want to use this or other component libraries in my project, what license applies to it?

Advanced REST Client allows usage of any part of it with [Apache 2.0 license](https://github.com/advanced-rest-client/arc-electron/blob/master/LICENSE.md), API Console, that uses the same components, is licensed with [CPAL 1.0](https://github.com/mulesoft/api-console/blob/master/LICENSE.md) and this repo (and all other deprecated component repos) doesn't contain any license, which is quite contradicting. Could you add license(s) please?

**Comment by jarrodek** [comment]
Hi @deiteris 
I am sorry for the late response. I was on vacation. The license is Apache 2-0 (defined in package.json file). I will add an appropriate license to the repo.
